AWSTemplateFormatVersion: '2010-09-09'
Description: Resource stack for Atlas of Oregon Lakes Frontend
Resources:
  AppRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20221006/iam/application_role.template.yml
      Parameters:
        Name: aol-frontend
        VpcStackName: vpc-cloud
  Bucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20221006/s3/bucket.template.yml
      Parameters:
        IamPrinicipleArn: !GetAtt 'AppRole.Outputs.RoleArn'
        KmsKey: !GetAtt 'AppRole.Outputs.KmsKeyArn'
        EnableEncryption: false
        EnableCloudFront: true
        BucketName: aol-frontend
        BucketRealm: cloud.wdt.pdx.edu
        AccessPath: active/*
        DeletionPolicy: Retain
  Distribution:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20221006/cloudfront/distribution.template.yml
      Parameters:
        Certificate: arn:aws:acm:us-east-1:921749119607:certificate/2fd5a7ef-795e-42b6-89df-570ac19cfb12
        HostedZone: oregonlakesatlas.org
        DomainName: oregonlakesatlas.org
        S3Origin: !GetAtt 'Bucket.Outputs.S3Endpoint'
        S3OriginPath: /active
        S3OriginAccessIdentity: !GetAtt 'Bucket.Outputs.CloudFrontOAI'
Parameters: {}
