AWSTemplateFormatVersion: '2010-09-09'
Description: Resource stack for Atlas of Oregon Lakes Frontend
Resources:
  AppRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20210115/iam/application_role.template.yml
      Parameters:
        Name: aol-frontend
        VpcStackName: vpc-prod
        EnableParameterEncryption: false
  Bucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20210115/s3/bucket.template.yml
      Parameters:
        IamPrinicipleArn: !GetAtt 'AppRole.Outputs.RoleArn'
        EnableEncryption: false
        EnableCloudFront: true
        BucketName: aol-frontend
        BucketRealm: wdt.pdx.edu
        BucketRegion: us-west-2
        AccessIdentityPath: active/*
        DeletionPolicy: Retain
  Distribution:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation-templates.wdt.pdx.edu/20210115/cloudfront/distribution.template.yml
      Parameters:
        Certificate: arn:aws:acm:us-east-1:921749119607:certificate/73aac8b0-db34-4498-b80f-1b8a13b1c43a
        HostedZone: oregonlakesatlas.org
        DomainName: oregonlakesatlas.org
        S3Origin: !GetAtt 'Bucket.Outputs.S3Endpoint'
        S3OriginPath: /active
        S3OriginAccessIdentity: !GetAtt 'Bucket.Outputs.CloudFrontOAI'
Parameters: {}
